keyid = {
    -- packs
        heli_pack           =0x02,
        thruster_pack       =0x03,
        hydro_pack          =0x04,
    -- helmets
        sonic_summoner      =0x05,
        o2_mask             =0x06,
        pilots_helmet       =0x07,
    -- gadgets
        swingshot           =0x0c,
        hydrodisplacer      =0x16,
        trespasser          =0x1a,
        metal_detector      =0x1b,
        hologuise           =0x1f,
        pda                 =0x20,
    -- boots
        magneboots          =0x1c,
        grindboots          =0x1d,
    -- items
        hoverboard          =0x1e,
        map_o_matic         =0x21,
        bolt_grabber        =0x22,
        persuader           =0x23,
        zoomerator          =0x30,
        raritanium          =0x31,
        codebot             =0x32,
        premium_nanotech    =0x34,
        ultra_nanotech      =0x35,
    -- vendor weapons
        devastator          =0x0b,
        visibomb            =0x0d,
        taunter             =0x0e,
        blaster             =0x0f,
        pyrociter           =0x10,
        mine_glove          =0x11,
        walloper            =0x12,
        tesla_claw          =0x13,
        glove_of_doom       =0x14,
        drone_device        =0x18,
        decoy_glove         =0x19,
    -- check weapons
        bomb_glove          =0x0a, -- currently unused
        suck_cannon         =0x09,
        morph_o_ray         =0x15,
        ryno                =0x17,
        
    -- infobots
        -- novalis=1,
        -- aridia=2,
        -- kerwan=3,
        -- eudora=4,
        -- rilgar=5,
        -- blarg=6,
        -- umbris=7,
        -- batalia=8,
        -- gaspar=9,
        -- orxon=10,
        -- pokitaru=0xb,
        -- hoven=0xc,
        -- gemlik=0xd,
        -- oltanis=0xe,
        -- quartu=0xf,
        -- kalebo=0x10,
        -- fleet=0x11,
        -- veldin=0x12,
    }