keyid = {
    -- packs
        heli_pack           ={0x02, true},
        thruster_pack       ={0x03, true},
        hydro_pack          ={0x04, true},
    -- helmets
        sonic_summoner      ={0x05, true},
        o2_mask             ={0x06, true},
        pilots_helmet       ={0x07, true},
    -- gadgets
        swingshot           ={0x0c, true},
        hydrodisplacer      ={0x16, true},
        trespasser          ={0x1a, true},
        metal_detector      ={0x1b, true},
        hologuise           ={0x1f, true},
        pda                 ={0x20, true},
    -- boots
        magneboots          ={0x1c, true},
        grindboots          ={0x1d, true},
    -- items
        hoverboard          ={0x1e, false},
        map_o_matic         ={0x21, false},
        bolt_grabber        ={0x22, false},
        persuader           ={0x23, false},
        zoomerator          ={0x30, false},
        raritanium          ={0x31, false},
        codebot             ={0x32, false},
        premium_nanotech    ={0x34, false},
        ultra_nanotech      ={0x35, false},
    -- vendor weapons
        devastator          ={0x0b, true},
        visibomb            ={0x0d, true},
        taunter             ={0x0e, true},
        blaster             ={0x0f, true},
        pyrociter           ={0x10, true},
        mine_glove          ={0x11, true},
        walloper            ={0x12, true},
        tesla_claw          ={0x13, true},
        glove_of_doom       ={0x14, true},
        drone_device        ={0x18, true},
        decoy_glove         ={0x19, true},
    -- check weapons
        bomb_glove          ={0x0a, true},
        suck_cannon         ={0x09, true},
        morph_o_ray         ={0x15, true},
        ryno                ={0x17, true},
        
    -- infobots
        -- novalis=1,
        -- aridia=2,
        -- kerwan=3,
        -- eudora=4,
        -- rilgar=5,
        -- blarg=6,
        -- umbris=7,
        -- batalia=8,
        -- gaspar=9,
        -- orxon=10,
        -- pokitaru=0xb,
        -- hoven=0xc,
        -- gemlik=0xd,
        -- oltanis=0xe,
        -- quartu=0xf,
        -- kalebo=0x10,
        -- fleet=0x11,
        -- veldin=0x12,
    }